version: '2'
services:
  php:
    build: ./docker/php
    volumes:
     - .:/var/www
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=homestead
      - DB_USER=homestead
      - DB_PASSWORD=secret
  nginx:
    build: ./docker/nginx
    ports:
     - "80:80"
    volumes:
     - .:/var/www
    links:
     - php
    depends_on:
     - php
  mysql:
    ports:
     - "33060:3306"
    image: 'percona:5.7'
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=password