version: '2'
services:
  php:
    build: ./docker/php
    container_name: standard_php
    volumes:
     - .:/var/www
    links:
      - mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=password
  redis:
    container_name: standard_redis
    image: 'redis:3.2-alpine'
    links:
      - php
  nginx:
    build: ./docker/nginx
    container_name: standard_nginx
    ports:
     - "80:80"
    volumes:
     - .:/var/www
    links:
     - php
    depends_on:
     - php
  mysql:
    ports:
     - "33060:3306"
    image: 'percona:5.7'
    container_name: standard_mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=password